### ISSUE TITLE
Adopt Markdown or Asciidoc for editing XACML specifications

### ISSUE THREAD

**Issue by cdanger** [oasis-tcs/xacml-spec#19]
The XACML TC currently uses MS-Word for creating and editing the specifications. However, on the contrary to MS Word, Markdown and Asciidoc are natively supported by Github and especially can be version-controlled with git. We could benefit from increased participation (and improved collaboration) if we adopted Markdown or Asciidoc instead as the tool of choice for maintaining our specs.

Some of the other OASIS TCs have been using Markdown for a while for their work. The OpenC2 TC in particular has done extensive work on documenting their procedures related to the use of Markdown. (Also the TOSCA TC for instance have shifted to Markdown.) These procedures can be found here:
https://github.com/oasis-tcs/openc2-tc-ops
and their work related to Markdown can be found here:
https://github.com/oasis-tcs/openc2-tc-ops/blob/main/Documentation-Norms.md

Markdown and Asciidoc are both supported by Github. There are pros and cons in either format. Although I prefer Asciidoc because better / more formally standardized, most TC participants are probably more familiar with Markdown. Open to discussion.

TODO: find out if another OASIS TC has been using Asciidoc.

**Comment by humantypo** [comment]
Oasis has said that it will assist with Markdown conversion to "specification" formats (as it has with other TCs). Asciidoc is not being used by any other [active] TC at the moment. Based on our call today, it looks like Markdown is the way to go moving forward. I will request a template from Oasis.

**Comment by humantypo** [comment]
For reference, here is the v3.1 markdown template: 
https://groups.oasis-open.org/viewdocument/starter-document-for-extensible-acc?CommunityKey=67afe552-0921-49b7-9a85-018dc7d3ef1d&tab=librarydocuments&MessageKey=62dbc27e-65c2-4a04-b322-e9279f2ef754

**Comment by humantypo** [comment]
Here is the markdown template for v4.0

[xacml-v4.0-csd01.zip](https://github.com/user-attachments/files/16145591/xacml-v4.0-csd01.zip)

Per Oasis:
The starter document package (.zip) contains the following files and directories:
- a markdown file (.md) ... this is the main template or starter document, customized with titles and other elements for this Work Product
- a directory "styles" containing an HTML style sheet (.css) (some .css files are permanently installed online - see "README" file.)
- a directory "images" containing an example image file
- a "README" text file with important instructions

**Comment by cdanger** [comment]
> Here is the markdown template for v4.0
> 
> [xacml-v4.0-csd01.zip](https://github.com/user-attachments/files/16145591/xacml-v4.0-csd01.zip)
> 
> Per Oasis: The starter document package (.zip) contains the following files and directories:
> 
>     * a markdown file (.md) ... this is the main template or starter document, customized with titles and other elements for this Work Product
> 
>     * a directory "styles" containing an HTML style sheet (.css) (some .css files are permanently installed online - see "README" file.)
> 
>     * a directory "images" containing an example image file
> 
>     * a "README" text file with important instructions

I assume this zip content is exactly what you put on the [xacml-4.0-core spec branch](https://github.com/oasis-tcs/xacml-spec/tree/xacml-4.0-core-spec)? So that's good, thanks. Go for markdown.
