### ISSUE TITLE
Make MustBePresent attribute in AttributeDesignator and AttributeSelector default false.

### ISSUE THREAD

**Issue by steven-legg** [oasis-tcs/xacml-spec#20]
I almost never set the MustBePresent XML attribute in AttributeDesignator and AttributeSelector elements to true, but it is a required XML attribute so I have to include it. It ends up being extra clutter. If MustBePresent were default false then it would rarely appear. Others' mileage may vary.

**Comment by cdanger** [comment]
Agreed.  I would say the same for IncludeInResult (already addressed in #18), ReturnPolicyIdList and CombinedDecision, but maybe create separate issues for those.

**Comment by steven-legg** [comment]
> but maybe create separate issues for those

Done.

**Comment by steven-legg** [comment]
We seem to have consensus on this so I will make this change to the working draft and close the issue.

**Comment by steven-legg** [comment]
MustBePresent changed to default false in the working draft.
