### ISSUE TITLE
Make the ReturnPolicyIdList attribute default false.

### ISSUE THREAD

**Issue by steven-legg** [oasis-tcs/xacml-spec#26]
The ReturnPolicyIdList attribute is usually set to false in normal operation but it is a required XML attribute so has to be included in every request. The JSON profile makes it optional, default false. The core specification for XACML 4.0 could also make it default false to reduce clutter.

**Comment by steven-legg** [comment]
No one has spoken against this change so unless there are any immediate objections I will make this change to the working draft and close the issue.

**Comment by cdanger** [comment]
OK for me :+1:

**Comment by steven-legg** [comment]
ReturnPolicyIdList changed to default false in the working draft.
