### ISSUE TITLE
Make the CombinedDecision attribute default false.

### ISSUE THREAD

**Issue by steven-legg** [oasis-tcs/xacml-spec#27]
The CombinedDecision attribute is only useful in requests for multiple decisions, and even then it wouldn't necessarily be set to true, but it is a required XML attribute so has to be included in every request. The JSON profile makes it optional, default false. The core specification for XACML 4.0 could also make it default false to reduce clutter.

**Comment by steven-legg** [comment]
This seems uncontroversial. Unless there are any immediate objections I will make this change to the working draft and close the issue.

**Comment by cdanger** [comment]
OK for me :+1:

**Comment by steven-legg** [comment]
CombinedDecision changed to default false in the working draft.
